language: c

env:
  matrix:
    # standard builds
    - CC=gcc
    - CC=clang
    # cross-compile using mingw
    - CC= PLATFORM="mingw32" ARCH="x86"
    - CC= PLATFORM="mingw32" ARCH="x86_64"

script: ./travis-ci-build.sh

notifications:
  irc:
    channels:
      - "irc.freenode.org#ebx"
    on_success: change
    on_failure: always

sudo: false

addons:
  apt:
    packages:
      - binutils-mingw-w64-i686
      - gcc-mingw-w64-i686
      - binutils-mingw-w64-x86-64
      - gcc-mingw-w64-x86-64
      - gcc-mingw-w64
      - mingw-w64
